version: 0.2

phases:
  pre_build:
    commands:
      - echo "Fazendo login no Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 509399600589.dkr.ecr.us-east-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:-latest}

  build:
    commands:
      - echo "Construindo a imagem Docker..."
      - docker build -t 509399600589.dkr.ecr.us-east-1.amazonaws.com/devops:latest .

  post_build:
    commands:
      - echo "Enviando imagem para o ECR..."
      - docker push 509399600589.dkr.ecr.us-east-1.amazonaws.com/devops:latest
      - echo "Gerando imagedefinitions.json..."
      - printf '[{"name":"go-api","imageUri":"%s"}]' "509399600589.dkr.ecr.us-east-1.amazonaws.com/devops:latest" > imagedefinitions.json


artifacts:
  files:
    - imagedefinitions.json
