version: 0.2

env:
  variables:
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo "Fazendo login no ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 509399600589.dkr.ecr.us-east-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:-latest}
      - echo "Usando tag: $IMAGE_TAG"

  build:
    commands:
      - echo "Construindo imagem..."
      - docker build -t 509399600589.dkr.ecr.us-east-1.amazonaws.com/go-api:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Fazendo push para o ECR..."
      - docker push 509399600589.dkr.ecr.us-east-1.amazonaws.com/go-api:$IMAGE_TAG
      - echo "Gerando imagedefinitions.json..."
      - printf '[{"name":"go-api","imageUri":"%s"}]' "509399600589.dkr.ecr.us-east-1.amazonaws.com/go-api:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
