definitions:
  domain.ChatMessage:
    properties:
      content:
        type: string
      conversation_id:
        type: string
      created_at:
        type: string
      id:
        type: string
      user_id:
        type: string
    type: object
  domain.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /chat/send:
    post:
      consumes:
      - application/json
      description: Recebe uma mensagem do usuário, envia para o Dify e retorna a resposta
        com possível conversation_id
      parameters:
      - description: Mensagem do usuário
        in: body
        name: chatMessage
        required: true
        schema:
          $ref: '#/definitions/domain.ChatMessage'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Envia uma mensagem para o Dify
      tags:
      - chat
  /health:
    get:
      description: Verifica se a API está rodando
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health Check
      tags:
      - health
  /users:
    post:
      consumes:
      - application/json
      description: Cria um usuário com nome, email e id
      parameters:
      - description: Usuário a ser criado
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Cria um novo usuário
      tags:
      - users
swagger: "2.0"
